pipeline {
    agent any
    tools { 
        maven 'Maven_local' 
        jdk 'JAVA8'
        // docker 'DockerLocal' 
    }
    stages {
        stage ('Initialize') {
            steps {
                bat '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

      stage ('Build') {
            steps {
               bat 'mvn -Dmaven.test.failure.ignore=true install'
                //
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }

//    stage('Build Maven Image') {
//         docker.build("mavenbuild") }
   
//    stage('Run Maven Container') {
       
//         //Remove maven-build-container if it exists
//         bat "docker rm -f maven-build-container"
        
//         //Run maven image
//         bat "docker run --rm --name maven-build-container maven-build"
//    }
   
//    stage('Deploy Spring Boot Application') {
        
//          //Remove maven-build-container if it exists
//         bat " docker rm -f java-deploy-container"
       
//         bat "docker run --name java-deploy-container --volumes-from maven-build-container -d -p 8080:8080 hellodevops/testrepo:springbootdemo"
//    }
    }
}

// pipeline {
//   environment {
//     registry = "hellodevops/testrepo"
//     registryCredential = 'hellodevops'
//     dockerImage = ''
//   }
//   agent any
//   stages {
 
//     stage('Building image') {
//       steps{
//         script {
//           dockerImage = docker.build registry + ":$BUILD_NUMBER"
//         }
//       }
//     }
//     stage('Deploy Image') {
//       steps{
//         script {
//           docker.withRegistry( '', registryCredential ) {
//             dockerImage.push()
//           }
//         }
//       }
//     }
//     stage('Remove Unused docker image') {
//       steps{
//         bat "docker rmi $registry:$BUILD_NUMBER"
//       }
//     }
//   }
// }